models:
  - name: "deepseek-v3"
    provider: "together_ai"
    model_id: "deepseek-ai/DeepSeek-V3.1"
    default_params:
      temperature: 0
      max_tokens: 8192
      top_p: 1
      reasoning: True

  - name: "deepseek-r1"
    provider: "together_ai"
    model_id: "deepseek-ai/DeepSeek-R1"
    default_params:
      temperature: 0
      max_tokens: 8192
      top_p: 1
      reasoning: True

  - name: "gemini-2.5-flash"
    provider: "gemini"
    model_id: "gemini-2.5-flash"
    default_params:
      temperature: 0
      max_tokens: 512
      top_p: 1
      thinking_budget: 8192
  
  - name: "gpt-4o"
    provider: "openai"
    model_id: "gpt-4o"
    default_params:
      temperature: 0.7
      max_tokens: 512
      top_p: 0.9